# Generated by Django 2.0.7 on 2018-07-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='closed_at',
        ),
    ]
