# Generated by Django 2.0.7 on 2018-07-26 01:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0002_remove_mission_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(default='POLYGON EMPTY', srid=4326),
        ),
    ]
