# Generated by Django 2.1 on 2018-08-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0003_mission_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('clearance_id', models.TextField(primary_key=True, serialize=False)),
                ('created_by', models.TextField()),
                ('state', models.TextField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
