# Generated by Django 2.0.7 on 2018-08-05 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0003_mission_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'permissions': (('read_mission', 'Read mission'), ('write_mission', 'Write mission'))},
        ),
        migrations.AlterField(
            model_name='mission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
