# Generated by Django 2.0.7 on 2018-08-18 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icarus_backend', '0004_auto_20180805_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={},
        ),
        migrations.AddField(
            model_name='mission',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
