# Generated by Django 2.0.7 on 2018-08-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0006_auto_20180818_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='mission_id',
            new_name='id',
        ),
    ]
