# Generated by Django 2.0.7 on 2018-08-22 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0007_auto_20180818_1832'),
        ('icarus_backend', '0005_mission_clearance'),
    ]

    operations = [
    ]
