# Generated by Django 2.0.7 on 2018-08-22 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icarus_backend', '0008_merge_20180822_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('drone_id', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('manufacturer', models.TextField()),
                ('drone_type', models.TextField()),
                ('color', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
