# Generated by Django 2.0.7 on 2018-08-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0009_drone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='drone_id',
            new_name='id',
        ),
    ]
