# Generated by Django 2.0.7 on 2018-08-22 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0010_auto_20180822_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
