# Generated by Django 2.0.7 on 2018-08-22 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icarus_backend', '0012_auto_20180822_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icarus_backend.Drone')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icarus_backend.Mission')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('drone', 'mission')},
        ),
    ]
