# Generated by Django 2.1 on 2018-08-23 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0015_auto_20180822_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
