# Generated by Django 2.1 on 2018-08-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0015_auto_20180822_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cors', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'corsheaders_corsmodel',
                'abstract': False,
            },
        ),
    ]
